### ISSUE TITLE
Handling Missing Data (genereal question)

### ISSUE THREAD

**Issue by michael135** [uber/orbit#266]
Can it handle the missing data?

From what I've tried, it doesn't accept `np.nan`.

Just dropping the rows with NaN from DataFrame is appropriate or there some more specific treatment exist in Orbit/ Pyro?

**Comment by steveyang90** [comment]
In most cases, dropping the rows with NaN is probably not the best approach.

For a couple of reasons, we left handling of missing data for the user to determine. First is because there are many different ways to handle it, and that'll be task-specific. Second, Pandas already has quite a bit of functionality for such cases. I'd recommend taking a look at the [resample](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) method
