### ISSUE TITLE
Is it possible to use an additional features (multivariate data)?

### ISSUE THREAD

**Issue by michael135** [uber/orbit#267]
Is it possible to use an additional features (multivariate data)?

I've looked thorough example and it seems that in claims data the only column which is used is a `claims` column.

Also it seems me in a toy example `claims data`, additional columns has informative information, to demonstrate the user of additional features (for educational purposes).

![image](https://user-images.githubusercontent.com/8559652/98256928-d0428b00-1f87-11eb-92b0-f11175b608d0.png)

**Comment by steveyang90** [comment]
Great question! We haven't yet implemented a multivariate time series response, but but LGT and DLT class of models allows for exogenous regressors in addition to a univariate response.

You can see an example of how to do that in this [tutorial](https://uber.github.io/orbit/tutorials/regression.html)

In the future we plan on implementing a model that also allows a multivariate response rather than just independent regressors
