### ISSUE TITLE
Holiday calendar support 

### ISSUE THREAD

**Issue by ramyahrgowda** [uber/orbit#272]
**Is your feature request related to a problem? Please describe.**
While sales forecasting, it is necessary that the model is given the input about the promotions, special events that are taken care of in the prophet model as the holiday effect. Does orbit support this feature?

**Comment by edwinnglabs** [comment]
> **Is your feature request related to a problem? Please describe.**
> While sales forecasting, it is necessary that the model is given the input about the promotions, special events that are taken care of in the prophet model as the holiday effect. Does orbit support this feature?

So if i understand your question correctly, you want to do some causal effect/scenario analysis with promos and events.  There are two parts: the data supply and the regression analysis.  We don't have an auto load of events based on the calendar like prophet.  However, if you provide them on your own (as a binary indicator) and input as the `regressor_col`, you should perform the analysis you want.  Since we want to focus on the modeling part, we don't cover extensive features engineering at this point.  Hope it answers your question.

**Comment by hassan-jvd90** [comment]
Hi @edwinnglabs , I'd like to contribute to this feature in orbit. I have some experience with Prophet and this might be useful here as well. 
Here is how I'd probably do this:
Use the holidays package: https://pypi.org/project/holidays/ to get country/location-based holidays and then create a binarized dataframe as suggested by you that can be consumed as a regressor. This might be served through utils/features. Let me know what you think. Thanks!

**Comment by edwinnglabs** [comment]
That should work @hassan-jvd90.  Thank you for bringing this up.  Originally, we don't want to do full automation of appending holidays / events within the model.  But what you suggested of making this as utilities is a good idea especially given building regression analysis tools is one of our focuses.  Feel free to create a PR on that.
