### ISSUE TITLE
Positivity constraint for predictions

### ISSUE THREAD

**Issue by candalfigomoro** [uber/orbit#517]
Is there a way to add a positivity constraint for predictions without having to apply log transforms (making it a multiplicative model)?

Thanks

**Comment by edwinnglabs** [comment]
It seems to me it would be hard do it without turning the model as multiplicative.
 Since our noise generation is symmetric and additive,  theoretically it's cannot guarantee non-negative outcomes that way unless we modify the model structure such as multiplicative noise or some link function e.g. poisson, negative binomial, ...

We do plan to create a different style of models to accomodate those needs. Unfortunately, they are not available yet.
