### ISSUE TITLE
Use demos and tutorials from master branch for PyPI Installation

### ISSUE THREAD

**Issue by kryptonite0** [uber/orbit#633]
The version of `orbit` installed via pip (1.0.17, ff628e16d2a53d1fbc094b1a5b3fa5ac049b5172) is not aligned with the documentation.

For example, `from orbit.models import DLT` does not work because there is no `DLT` class defined in the `__init__.py`.
The same import works when I install from `@dev` branch.

**Comment by edwinnglabs** [comment]
Hi @kryptonite0 I see the confusion.  Hope this can answer your question:
1. the default page in this `github` is in `dev` branch which means all the syntax are based on the version you install by either installing locally along with `git clone` or simply by `$ pip install git+https://github.com/uber/orbit.git@dev
`. This way, you should be able to enjoy all the syntax up on the dev [github page](https://github.com/uber/orbit/tree/dev)
2. An alternative is to switch to `master` branch.  You can check out [here](https://github.com/uber/orbit/tree/master) . For the tutorials on master branch version, you can also check out [here](https://orbit-ml.readthedocs.io/en/stable/#)

At the moment, we are transitioning from v1.0 to v1.1 which has some major changes in syntax.  That's why you will find some parts in dev version incompatible with the master version.

**Comment by edwinnglabs** [comment]
I also edited the `dev` branch to clarify this.
